name: 04- contexts
on:
  push
jobs:
  echo-data:
      runs-on: ubuntu-latest
      steps:
        - name: display infomration
          run: |
            echo "event name: ${{ github.events_name }} "
            echo " ref: ${{ github.ref }}"
            echo " SHA: ${{ github.sha }}"
            echo "actor: ${{ github.actor }} "
            echo "runid: ${{ github.run_id }}"

        # - name: retrieve varaiables
        #   run: echo "varaible value: ${{ vars.MY_VAR }}"
        
