name: 04- contexts
run-name: 06 - contexts | DEBUG - ${{ inputs.debug }}

on: 
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERWRITTEN_VAR: "workflow"
jobs:
  echo-data:
      runs-on: ubuntu-latest
      env:
        MY_JOB_VAR: 'JOB' 
      steps:
        - name: display infomration
          run: |
            echo "event name: ${{ github.events_name }} "
            echo " ref: ${{ github.ref }}"
            echo " SHA: ${{ github.sha }}"
            echo "actor: ${{ github.actor }} "
            echo "runid: ${{ github.run_id }}"

        - name: retrieve varaiables
          run: |
            echo "varaible value: ${{ vars.MY_VAR }}"
        
