name: 18.1 - reusable workflows - Reusable defination

on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true
    outputs:
       build-status:
         description: the status of the build process
         value: ${{ jobs.deploy.outputs.build-status }}
       url:
         description: the url of the deployed version
         value: $ {{ jobs.deploy.outputs.build-status }}
        

jobs: 
   deploy:
     runs-on: ubuntu-latest
     outputs:
       build-status: ${{ steps.build.outputs.build-status }}
       url: ${{ steps.deploy.outputs.url }}
     steps:
       - name: checkout repo
         uses: actions/checkout@v4
       - name: Build
         id: build
         run: |
           echo "building using directory ${{ inputs.target-directory }}"
           echo "build-status=success">> "$GITHUB_OUTPUT"
       - name: Deploy
         id: deploy
         run: |
           echo "Deploying build artifacts"
           echo "url=https://www.google.com" >> "$GITHUB_OUTPUT"
